#+title: projects
#+OPTIONS: \n:t title:nil
#+include: style_and_nav.org
* /experiments/
:properties:
:CUSTOM_ID: oscillator
:end:
The current [[file:oscillator.org][project]] in development.
[[file:oscillator.org::#code][Code]] will change but the main idea is there.
* writing C for music
:properties:
:CUSTOM_ID: writing_c_for_music
:end:
A fast pass for some chapters from the book [[https://mitpress.mit.edu/9780262014465/the-audio-programming-book/][The audio programming book]] for writing the first audio lines in C.
The start of the book with some stuff implemented are on [[https://github.com/awfulbytes/the_audio_programming_session][github]] but I really recommend to follow the book. It will clear up consepts like Makefile syntax and how to setup a project from scratch. Without clicking buttons...
------
------
@@html:<h1 class="title">other projects</h1>@@
* FEA on acrylic tiles
:properties:
:CUSTOM_ID: fea_acrylic_tiles
:end:
A basic Finite Element Analysis in FreeCad for simulating static forces elevated on feet.
For more information go to the [[https://gitlab.com/goodvibrations32/tiles][gitlab repo]]. FEMMesh[[https://gmsh.info/][Gmsh]] and [[https://www.calculix.de/][Ccx]] solver *pre* _FreeCad 1.0_ used. I have no idea what is the state of FEA in [[https://www.freecad.org/][FreeCad]] nowdays.
* a python interactive /puzzle/ game
:properties:
:CUSTOM_ID: python_qr_game
:end:
[[https://gitlab.com/goodvibrations32/puzzle][The game]] is not finished but a proof of concept for a /"treasure hunt"-like/ game where qr-codes printed on paper and a camera on a raspberry pi 4 is reading and placing the corresponding image piece. The goal is... you guessed it... to find all hidden qr's in the room and complete the image.
/P.S. I would like to find time to revive that one but it is working when archived./
* my bachelor thesis in org mode
:properties:
:CUSTOM_ID: bachelor_thesis
:end:
[[https://github.com/hmu-mech-npap/diss.tn.doc/][Reproducible documents]] are difficult to make and more over to keep in sync with changes on the dataset. Running code when a plot is needed differs a lot from running the script, producing the image, open the file manager, find the plot (assuming naming done correctly in the script) and importing the image to a rich text manipulation program i.e. Libre Office Writer or MS Word.
